import simg from '../images/service/card-mision.jpeg'
import simg2 from '../images/service/card-vision.png'
import simg3 from '../images/service/card-valores.png'
import simg4 from '../images/service/card-politicas.jpeg'

import sImgS1 from '../images/service-single/primera-mision.jpg'
import sImgS2 from '../images/service-single/img-2.jpg'
import sImgS3 from '../images/service-single/img-3.jpg'
import sImgS4 from '../images/service-single/cuarta-politica.jpg'

import sSingleimg1 from '../images/service-single/2.jpg'
import sSingleimg2 from '../images/service-single/3.jpg'

import frutoarea from '../images/service/fruto/iconoCapuslas.webp';
import frutocomunicacon from '../images/service/fruto/fruto-medios-comunicacion.webp';

const Services = [


    {
        Id: '1',
        sImg: simg,
        sImgS: sImgS1,
        sTitle: 'Cápsula 1',
        description: 'EL GENIO DE JESÚS: El hombre que lo cambió todo ',
        videoUrl: 'https://drive.google.com/file/d/15bISYKYZGOgnx9Ot_8jmJ3NNrQwlGfD2/view?usp=sharing',
        des2: 'Fecha: 20 de Octubre',
        des3: 'One way to categorize the activities is in terms of the professional’s area of expertise such as competitive analysis, corporate strategy the activities',
        image: frutoarea,
        ssImg1: sSingleimg1,
        ssImg2: sSingleimg2,
    },
    {
        Id: '1',
        sImg: simg,
        sImgS: sImgS1,
        sTitle: 'Cápsula 7',
        description: 'CÓMO DAR RETROALIMENTACIÓN DE MANERA EFECTIVA: Retroalimentación con permiso',
        videoUrl: 'https://drive.google.com/file/d/1bgAAhH77v2IP7czAMsDikdrz1Q5-HzTX/view?usp=sharing',
        des2: 'Fecha: 13 de Octubre',
        des3: 'One way to categorize the activities is in terms of the professional’s area of expertise such as competitive analysis, corporate strategy the activities',
        image: frutoarea,
        ssImg1: sSingleimg1,
        ssImg2: sSingleimg2,
    },
    {
        Id: '1',
        sImg: simg,
        sImgS: sImgS1,
        sTitle: 'Cápsula 6',
        description: 'CÓMO DAR RETROALIMENTACIÓN DE MANERA EFECTIVA: Lo que comunicas sin palabras',
        videoUrl: 'https://drive.google.com/file/d/1ZSonUryfW-LBVeGyNqizg5rcGPL1HsPQ/view?usp=sharing',
        des2: 'Fecha: 2 de Octubre',
        des3: 'One way to categorize the activities is in terms of the professional’s area of expertise such as competitive analysis, corporate strategy the activities',
        image: frutoarea,
        ssImg1: sSingleimg1,
        ssImg2: sSingleimg2,
    },
    {
        Id: '1',
        sImg: simg,
        sImgS: sImgS1,
        sTitle: 'Cápsula 5',
        description: 'CÓMO DAR RETROALIMENTACIÓN DE MANERA EFECTIVA: El poder de una palabra',
        videoUrl: 'https://drive.google.com/file/d/1ioqgwGkspnjRtS4peHoukjvz3-dykM-k/view?usp=sharing',
        des2: 'Fecha: 29 de Septiembre',
        des3: 'One way to categorize the activities is in terms of the professional’s area of expertise such as competitive analysis, corporate strategy the activities',
        image: frutoarea,
        ssImg1: sSingleimg1,
        ssImg2: sSingleimg2,
    },
    {
        Id: '1',
        sImg: simg,
        sImgS: sImgS1,
        sTitle: 'Cápsula 4',
        description: 'CÓMO DAR RETROALIMENTACIÓN DE MANERA EFECTIVA: Claridad y equilibrio',
        videoUrl: 'https://drive.google.com/file/d/1_pPPIba-6sEXdxAgLacmwJkk5hLE6OS0/view?usp=sharing',
        des2: 'Fecha: 22 de Septiembre',
        des3: 'One way to categorize the activities is in terms of the professional’s area of expertise such as competitive analysis, corporate strategy the activities',
        image: frutoarea,
        ssImg1: sSingleimg1,
        ssImg2: sSingleimg2,
    },
    {
        Id: '1',
        sImg: simg,
        sImgS: sImgS1,
        sTitle: 'Cápsula 3',
        description: 'CÓMO DAR RETROALIMENTACIÓN DE MANERA EFECTIVA: Menos es más',
        videoUrl: 'https://drive.google.com/file/d/1Z5gGKZC4vevjyNdrtUzN1xNkPH2InVUD/view?usp=sharing',
        des2: 'Fecha: 8 de Septiembre',
        des3: 'One way to categorize the activities is in terms of the professional’s area of expertise such as competitive analysis, corporate strategy the activities',
        image: frutoarea,
        ssImg1: sSingleimg1,
        ssImg2: sSingleimg2,
    },
    {
        Id: '1',
        sImg: simg,
        sImgS: sImgS1,
        sTitle: 'Cápsula 2',
        description: 'CÓMO DAR RETROALIMENTACIÓN DE MANERA EFECTIVA: Construir en vez de destruir',
        videoUrl: 'https://drive.google.com/file/d/1Cd49M887l3YMfWKe5rLEBdAPXHnD5lKw/view?usp=sharing',
        des2: 'Fecha: 1 de Septiembre',
        des3: 'One way to categorize the activities is in terms of the professional’s area of expertise such as competitive analysis, corporate strategy the activities',
        image: frutoarea,
        ssImg1: sSingleimg1,
        ssImg2: sSingleimg2,
    },
    {
        Id: '1',
        sImg: simg,
        sImgS: sImgS1,
        sTitle: 'Cápsula 1',
        description: 'CÓMO DAR RETROALIMENTACIÓN DE MANERA EFECTIVA: Privacidad y oportunidad',
        videoUrl: 'https://drive.google.com/file/d/1dBY6QrOhO7e862W2FMGZtCcrw1jdMZ0g/view?usp=sharing',
        des2: 'Fecha: 25 de Agosto',
        des3: 'One way to categorize the activities is in terms of the professional’s area of expertise such as competitive analysis, corporate strategy the activities',
        image: frutoarea,
        ssImg1: sSingleimg1,
        ssImg2: sSingleimg2,
    },
    {
        Id: '1',
        sImg: simg,
        sImgS: sImgS1,
        sTitle: 'Cápsula 6',
        description: 'AFINANDO LA ESTRATEGIA: Alinea, asigna y avanza',
        videoUrl: 'https://drive.google.com/file/d/1U-XkDpxft-L1r5-AxeWHy3haNGYb2zFJ/view?usp=sharing',
        des2: 'Fecha: 18 de Agosto',
        des3: 'One way to categorize the activities is in terms of the professional’s area of expertise such as competitive analysis, corporate strategy the activities',
        image: frutoarea,
        ssImg1: sSingleimg1,
        ssImg2: sSingleimg2,
    },

    {
        Id: '1',
        sImg: simg,
        sImgS: sImgS1,
        sTitle: 'Cápsula 5',
        description: 'AFINANDO LA ESTRATEGIA: Enfoca lo que suma',
        videoUrl: 'https://drive.google.com/file/d/1FygwuFcByJdA1aDfuS4cVSEaZwcdIoBI/view?usp=sharing',
        des2: 'Fecha: 11 de Agosto',
        des3: 'One way to categorize the activities is in terms of the professional’s area of expertise such as competitive analysis, corporate strategy the activities',
        image: frutoarea,
        ssImg1: sSingleimg1,
        ssImg2: sSingleimg2,
    },

    {
        Id: '1',
        sImg: simg,
        sImgS: sImgS1,
        sTitle: 'Cápsula 4',
        description: 'AFINANDO LA ESTRATEGIA: Anticipa con sabiduría',
        videoUrl: 'https://drive.google.com/file/d/1PvXnrPYAlZ_FwfIvq4LXiLDV2EjjzI6d/view?usp=sharing',
        des2: 'Fecha: 4 de Agosto',
        des3: 'One way to categorize the activities is in terms of the professional’s area of expertise such as competitive analysis, corporate strategy the activities',
        image: frutoarea,
        ssImg1: sSingleimg1,
        ssImg2: sSingleimg2,
    },
    {
        Id: '1',
        sImg: simg,
        sImgS: sImgS1,
        sTitle: 'Cápsula 3',
        description: 'AFINANDO LA ESTRATEGIA: Enfócate en lo que sí importa',
        videoUrl: 'https://drive.google.com/file/d/1w6bVHEwqP6PIaYns7MJntRvBN3mOMU6-/view?usp=sharing',
        des2: 'Fecha: 21 de Julio',
        des3: 'One way to categorize the activities is in terms of the professional’s area of expertise such as competitive analysis, corporate strategy the activities',
        image: frutoarea,
        ssImg1: sSingleimg1,
        ssImg2: sSingleimg2,
    },
    {
        Id: '1',
        sImg: simg,
        sImgS: sImgS1,
        sTitle: 'Cápsula 2',
        description: 'AFINANDO LA ESTRATEGIA: Haz lo que otros no hacen',
        videoUrl: 'https://drive.google.com/file/d/1b5bMn_w6MxIxR5A6-Q2CUtkRRJBtpAp-/view?usp=sharing',
        des2: 'Fecha: 14 de Julio',
        des3: 'One way to categorize the activities is in terms of the professional’s area of expertise such as competitive analysis, corporate strategy the activities',
        image: frutoarea,
        ssImg1: sSingleimg1,
        ssImg2: sSingleimg2,
    },

    {
        Id: '1',
        sImg: simg,
        sImgS: sImgS1,
        sTitle: 'Cápsula 1',
        description: 'AFINANDO LA ESTRATEGIA: Traduciendo la visión en pasos concretos',
        videoUrl: 'https://drive.google.com/file/d/1TOSYVBiVRzNAePBWmB3xue20DtssGELb/view?usp=sharing',
        des2: 'Fecha: 7 de Julio',
        des3: 'One way to categorize the activities is in terms of the professional’s area of expertise such as competitive analysis, corporate strategy the activities',
        image: frutoarea,
        ssImg1: sSingleimg1,
        ssImg2: sSingleimg2,
    },


    {
        Id: '1',
        sImg: simg,
        sImgS: sImgS1,
        sTitle: 'Cápsula 8',
        description: 'DISERNIMIENTO ESTRATEGICO: Decidir, aunque no guste',
        videoUrl: 'https://drive.google.com/file/d/1gioFvFpxETtvldC3XV6MQVxWt4ej7jQ8/view?usp=sharing',
        des2: 'Fecha: 30 de Junio',
        des3: 'One way to categorize the activities is in terms of the professional’s area of expertise such as competitive analysis, corporate strategy the activities',
        image: frutoarea,
        ssImg1: sSingleimg1,
        ssImg2: sSingleimg2,
    },

    {
        Id: '1',
        sImg: simg,
        sImgS: sImgS1,
        sTitle: 'Cápsula 1',
        description: 'DISERNIMIENTO ESTRATEGICO: Ver mas alla de lo aparente',
        videoUrl: 'https://drive.google.com/file/d/1eCE_OB1k9rctoVZ1eZFNA37WQTIVkbj1/view?usp=sharing',
        des2: 'Fecha: 12 de Mayo',
        des3: 'One way to categorize the activities is in terms of the professional’s area of expertise such as competitive analysis, corporate strategy the activities',
        image: frutoarea,
        ssImg1: sSingleimg1,
        ssImg2: sSingleimg2,
    },
    {
        Id: '1',
        sImg: simg,
        sImgS: sImgS1,
        sTitle: 'Cápsula 2',
        description: 'DISERNIMIENTO ESTRATEGICO: Define con claridad aunque no tengas todo',
        videoUrl: 'https://drive.google.com/file/d/1wnDjzl3JwjrKt9R55XyrXWtl9WQvHma5/view?usp=drive_link',
        des2: 'Fecha: 19 de Mayo',
        des3: 'One way to categorize the activities is in terms of the professional’s area of expertise such as competitive analysis, corporate strategy the activities',
        image: frutoarea,
        ssImg1: sSingleimg1,
        ssImg2: sSingleimg2,
    },
    {
        Id: '12',
        sImg: simg,
        sImgS: sImgS1,
        sTitle: 'Cápsula 3',
        description: 'DISERNIMIENTO ESTRATEGICO: Profundiza, no te quedes en la superficie',
        videoUrl: 'https://drive.google.com/file/d/1vGX9kQZqKClwmGQj2Zmkz_vUxCQRvJJz/view?usp=sharing',
        des2: 'Fecha: 26 de Mayo',
        des3: 'One way to categorize the activities is in terms of the professional’s area of expertise such as competitive analysis, corporate strategy the activities',
        image: frutoarea,
        ssImg1: sSingleimg1,
        ssImg2: sSingleimg2,
    },
    {
        Id: '14',
        sImg: simg,
        sImgS: sImgS1,
        sTitle: 'Cápsula 5',
        description: 'DISERNIMIENTO ESTRATEGICO: Mente abierta, estrategia abierta',
        videoUrl: 'https://drive.google.com/file/d/1CNo9Vw_aNIRihr6SLHG0O_jPBZ0znxwr/view?usp=sharing',
        des2: 'Fecha: 9 de Junio',
        des3: 'One way to categorize the activities is in terms of the professional’s area of expertise such as competitive analysis, corporate strategy the activities',
        image: frutoarea,
        ssImg1: sSingleimg1,
        ssImg2: sSingleimg2,
    },
    {
        Id: '15',
        sImg: simg,
        sImgS: sImgS1,
        sTitle: 'Cápsula 6',
        description: 'DISERNIMIENTO ESTRATEGICO: Todo esta conectado',
        videoUrl: 'https://drive.google.com/file/d/1nSYaoRu4Kx3HPcc9EQG06Pk1mcD81loD/view?usp=sharing',
        des2: 'Fecha: 16 de Junio',
        des3: 'One way to categorize the activities is in terms of the professional’s area of expertise such as competitive analysis, corporate strategy the activities',
        image: frutoarea,
        ssImg1: sSingleimg1,
        ssImg2: sSingleimg2,
    },
    {
        Id: '13',
        sImg: simg,
        sImgS: sImgS1,
        sTitle: 'Cápsula 4',
        description: 'DISERNIMIENTO ESTRATEGICO: Conecta los puntos estrategicos',
        videoUrl: 'https://drive.google.com/file/d/1Ny40XaStz4VGYJ9k9ZfDeVC16ILYB59V/view?usp=sharing',
        des2: 'Fecha: 4 de Junio',
        des3: 'One way to categorize the activities is in terms of the professional’s area of expertise such as competitive analysis, corporate strategy the activities',
        image: frutoarea,
        ssImg1: sSingleimg1,
        ssImg2: sSingleimg2,
    },
    {
        Id: '1',
        sImg: simg,
        sImgS: sImgS1,
        sTitle: 'Cápsula 4',
        description: 'PENSAMIENTO VISIONARIO: Identificando signos de riesgo en nuestra organización',
        videoUrl: 'https://drive.google.com/file/d/1wlo75X1XYJxdIU7VXhpXNFYpeDGmWGB3/view?usp=sharing',
        des2: 'Fecha: 5 de Mayo',
        des3: 'One way to categorize the activities is in terms of the professional’s area of expertise such as competitive analysis, corporate strategy the activities',
        image: frutoarea,
        ssImg1: sSingleimg1,
        ssImg2: sSingleimg2,
    },
    {
        Id: '1',
        sImg: simg,
        sImgS: sImgS1,
        sTitle: 'Cápsula 1',
        description: 'PENSAMIENTO VISIONARIO: Liderazgo como Jesús',
        videoUrl: 'https://drive.google.com/file/d/1ZtNMieQxXH82z3VyjvBBoPg8nA4paSBi/view?usp=sharing',
        des2: 'Fecha: 7 de Abril',
        des3: 'One way to categorize the activities is in terms of the professional’s area of expertise such as competitive analysis, corporate strategy the activities',
        image: frutoarea,
        ssImg1: sSingleimg1,
        ssImg2: sSingleimg2,
    },
    {
        Id: '2',
        sImg: simg,
        sImgS: sImgS1,
        sTitle: 'Cápsula 2',
        description: 'PENSAMIENTO VISIONARIO: Enfocándonos en el futuro',
        videoUrl: 'https://drive.google.com/file/d/1ejKWh9Tb0BI73VfVty6naqkWxb6ueVpl/view?usp=drive_link',
        des2: 'Fecha: 21 de Abril',
        des3: 'One way to categorize the activities is in terms of the professional’s area of expertise such as competitive analysis, corporate strategy the activities',
        image: frutoarea,
        ssImg1: sSingleimg1,
        ssImg2: sSingleimg2,
    },
    {
        Id: '3',
        sImg: simg,
        sImgS: sImgS1,
        sTitle: 'Cápsula 3',
        description: 'PENSAMIENTO VISIONARIO: La innovación a través de la creatividad',
        videoUrl: 'https://drive.google.com/file/d/1u9l-uqN8u_50rGqauDDo09faDatLyHo2/view?usp=sharing',
        des2: 'Fecha: 28 de Abril',
        des3: 'One way to categorize the activities is in terms of the professional’s area of expertise such as competitive analysis, corporate strategy the activities',
        image: frutoarea,
        ssImg1: sSingleimg1,
        ssImg2: sSingleimg2,
    },
    {
        Id: '4',
        sImg: simg,
        sImgS: sImgS1,
        sTitle: 'Cápsula 3',
        description: 'A TODA VELOCIDAD HACIA EL EXITO GRACIAS POR SER NUESTRA FUERZA',
        videoUrl: 'https://drive.google.com/file/d/1V-Cp7yEQYqyTOMrll9Kiyp6ISK4Obu5T/view?usp=drive_link',
        des2: 'Fecha: 10 de Marzo',
        des3: 'One way to categorize the activities is in terms of the professional’s area of expertise such as competitive analysis, corporate strategy the activities',
        image: frutoarea,
        ssImg1: sSingleimg1,
        ssImg2: sSingleimg2,
    },
    {
        Id: '5',
        sImg: simg,
        sImgS: sImgS1,
        sTitle: 'Cápsula 4',
        description: 'A TODA VELOCIDAD HACIA EL EXITO GRACIAS POR SER NUESTRA FUERZA',
        videoUrl: 'https://drive.google.com/file/d/1s4ddiZlpYEGVaezbqGOn1CLAJxzfLw6C/view?usp=drive_link',
        des2: 'Fecha: 17 de Marzo',
        des3: 'One way to categorize the activities is in terms of the professional’s area of expertise such as competitive analysis, corporate strategy the activities',
        image: frutoarea,
        ssImg1: sSingleimg1,
        ssImg2: sSingleimg2,
    },
    {
        Id: '6',
        sImg: simg,
        sImgS: sImgS1,
        sTitle: 'Cápsula 5',
        description: 'MÁS QUE UN TRAYECTO, UN DESTINO: GRACIAS POR ACOMPAÑARNOS EN ESTE VIAJE',
        videoUrl: 'https://drive.google.com/file/d/141jW46ifuD2cvwYbhoMYDidM8OgLHmOB/view?usp=sharing',
        des2: 'Fecha: 24 de Marzo',
        des3: 'One way to categorize the activities is in terms of the professional’s area of expertise such as competitive analysis, corporate strategy the activities',
        image: frutoarea,
        ssImg1: sSingleimg1,
        ssImg2: sSingleimg2,
    },

    {
        Id: '7',
        sImg: simg2,
        sImgS: sImgS2,
        sTitle: 'Cápsula 1',
        description: 'CÓMO DAR FRUTO EN EL ÁREA DE EDUCACIÓN EN MI VIDA',
        videoUrl: 'https://drive.google.com/file/d/1RyvfLBq0b8UH24VWG9igaqPRF9hUynf3/view?usp=drive_link',
        des2: 'Fecha: 13 de Enero',
        des3: 'One way to categorize the activities is in terms of the professional’s area of expertise such as competitive analysis, corporate strategy the activities',
        image: frutoarea,  // Otra imagen opcional
        ssImg1: sSingleimg1,
        ssImg2: sSingleimg2,
    },

    {
        Id: '8',
        sImg: simg2,
        sImgS: sImgS2,
        sTitle: 'Cápsula 2',
        description: 'CÓMO DAR FRUTO EN EL ÁREA DE EDUCACIÓN EN MI VIDA',
        videoUrl: 'https://drive.google.com/file/d/1vZL8hKy8hk7lwc2jRVqQa4ar6gGqD_fU/view?usp=sharing',
        des2: 'Fecha: 20 de Enero',
        des3: 'One way to categorize the activities is in terms of the professional’s area of expertise such as competitive analysis, corporate strategy the activities',
        image: frutoarea,  // Otra imagen opcional
        ssImg1: sSingleimg1,
        ssImg2: sSingleimg2,
    },
    {
        Id: '9',
        sImg: simg2,
        sImgS: sImgS2,
        sTitle: 'Cápsula 3',
        description: 'CÓMO DAR FRUTO EN EL ÁREA DE EDUCACIÓN EN MI VIDA',
        videoUrl: 'https://drive.google.com/file/d/1AHFT59mdSMUsDT_cwEm25a-ra_RvySUX/view?usp=sharing',
        des2: 'Fecha: 27 de Enero',
        des3: 'One way to categorize the activities is in terms of the professional’s area of expertise such as competitive analysis, corporate strategy the activities',
        image: frutoarea,  // Otra imagen opcional
        ssImg1: sSingleimg1,
        ssImg2: sSingleimg2,
    },
    {
        Id: '10',
        sImg: simg2,
        sImgS: sImgS2,
        sTitle: 'Cápsula 4',
        description: 'CÓMO DAR FRUTO EN EL ÁREA DE EDUCACIÓN EN MI VIDA',
        videoUrl: 'https://drive.google.com/file/d/1RSNInLy1aXG0-vouP8EEMq2EiB8gCN5K/view?usp=sharing',
        des2: 'Fecha: 3 de Febrero',
        des3: 'One way to categorize the activities is in terms of the professional’s area of expertise such as competitive analysis, corporate strategy the activities',
        image: frutoarea,  // Otra imagen opcional
        ssImg1: sSingleimg1,
        ssImg2: sSingleimg2,
    },
    {
        Id: '11',
        sImg: simg,
        sImgS: sImgS1,
        sTitle: 'Cápsula 5',
        description: 'CÓMO DAR FRUTO EN EL ÁREA DE EDUCACIÓN EN MI VIDA',
        videoUrl: 'https://drive.google.com/file/d/1nHonNkMkpg5PGZBpXFXUeLEXlGW5CMvv/view?usp=sharing',
        des2: 'Fecha: 10 de Febrero',
        des3: 'One way to categorize the activities is in terms of the professional’s area of expertise such as competitive analysis, corporate strategy the activities',
        image: frutoarea,  // Aquí puedes agregar otra imagen si es necesario.
        ssImg1: sSingleimg1,
        ssImg2: sSingleimg2,
    },
    {
        Id: '12',
        sImg: simg,
        sImgS: sImgS1,
        sTitle: 'Cápsula 1',
        description: 'A TODA VELOCIDAD HACIA EL EXITO GRACIAS POR SER NUESTRA FUERZA',
        videoUrl: 'https://drive.google.com/file/d/1x2k2qj9MoVT2EnkEch2xOBdE9pt6oT61/view?usp=sharing',
        des2: 'Fecha: 24 de Febrero',
        des3: 'One way to categorize the activities is in terms of the professional’s area of expertise such as competitive analysis, corporate strategy the activities',
        image: frutoarea,
        ssImg1: sSingleimg1,
        ssImg2: sSingleimg2,
    },
    {
        Id: '13',
        sImg: simg,
        sImgS: sImgS1,
        sTitle: 'Cápsula 2',
        description: 'A TODA VELOCIDAD HACIA EL EXITO GRACIAS POR SER NUESTRA FUERZA',
        videoUrl: 'https://drive.google.com/file/d/1rT8pMhvJbTVUYXUOwoSNjzaZRCnoyz6K/view?usp=drive_link',
        des2: 'Fecha: 3 de Marzo',
        des3: 'One way to categorize the activities is in terms of the professional’s area of expertise such as competitive analysis, corporate strategy the activities',
        image: frutoarea,
        ssImg1: sSingleimg1,
        ssImg2: sSingleimg2,
    },


];

export default Services;
